
FROM ubuntu:20.04

RUN apt-get update && apt-get install -y python3-pip

WORKDIR /app

COPY requirements.txt /app/requirements.txt

RUN pip3 install --upgrade setuptools

RUN pip3 install -r requirements.txt

COPY . /app

#
# Containers communicate with the outside world through network ports and storage through volumes.
#
EXPOSE	5000

ENTRYPOINT [ "python3" ]

CMD [ "rest-server.py" ]
